list/urls.py
from django.urls import path

from list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_task_status
)


app_name = "list"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("toggle_status/<int:pk>/", toggle_task_status, name="task-toggle-status"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
]

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("list.urls", namespace="list")),
]

list/models.py
from datetime import datetime

from django.db import models


class Task(models.Model):
    STATUS_CHOICES = (
        ("done", "DONE"),
        ("not done", "NOT DONE"),
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default="not done")
    tags = models.ManyToManyField("Tag")

    class Meta:
        ordering = ["-status"]

    def save(self, *args, **kwargs):
        if self.status == "done" and not self.deadline:
            self.deadline = datetime.now()
        super().save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

list/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from list.form import TaskForm, TagForm
from list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "list/task_list.html"
    paginate_by = 10


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "list/task_form.html"
    success_url = reverse_lazy("list:task-list")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.status = "not done"
        task.save()
        form.save_m2m()
        return super().form_valid(form)


class TaskUpdateView(generic.edit.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("list:task-list")


class TaskDeleteView(generic.edit.DeleteView):
    model = Task
    success_url = reverse_lazy("list:task-list")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "list/tag_list.html"
    paginate_by = 10


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("list:tag-list")


class TagUpdateView(generic.edit.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("list:tag-list")


class TagDeleteView(generic.edit.DeleteView):
    model = Tag
    success_url = reverse_lazy("list:tag-list")


def toggle_task_status(request, pk):
    task = Task.objects.get(pk=pk)
    if task.status == "done":
        task.status = "not done"
    else:
        task.status = "done"
    task.save()
    return redirect("list:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To DO LIST</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'list:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'list:tag-list' %}">Tags</a></li>
</ul>

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'list:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'list:tag-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'list:tag-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>TODO List</h1>
    <a href="{% url 'list:task-create' %}" class="btn btn-primary">Add task</a>
    
    {% if task_list %}
        <ul class="list-group mt-3">
            {% for task in task_list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <h3>{{ task.content }}</h3>
                        <span class="badge {% if task.status == 'done' %}badge-success{% else %}badge-danger{% endif %}">{{ task.status }}</span>
                        <p>Created: {{ task.created_at|date:"F j, Y, g:i a" }}</p>
                        {% if task.deadline %}
                            <p>Deadline: {{ task.deadline|date:"F j, Y, g:i a" }}</p>
                        {% endif %}
                        <p>Tags: 
                            {% for tag in task.tags.all %}
                                {{ tag.name }}
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <a href="{% url 'list:task-update' pk=task.pk %}" class="btn btn-secondary">Update</a>
                        <a href="{% url 'list:task-delete' pk=task.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                    <div>
                        <form action="{% url 'list:task-toggle-status' task.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn {% if task.status == "done" %}btn-warning{% else %}btn-success{% endif %}">
                                {% if task.status == "done" %}Undo{% else %}Complete{% endif %}
                            </button>
                        </form>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no tasks.</p>
    {% endif %}
{% endblock %}